### PR TITLE
Bug 138

### LINKED ISSUE #138: Type initialiser for SchemaRegistry throws an exception
**Environment**
- Nuget Package: JsonSchema.Net
- Nuget Version: 1.10.5
- OS: Windows 10
- .Net Target: .NET Core 3.1.16, .NET 5.0.7

**Describe the bug**
An exception is thrown by the type initialiser for `ValidationOptions` that is caused by a `NullReferenceException` in the `SchemaRegistry` type initialiser:

```
System.TypeInitializationException: The type initializer for 'Json.Schema.ValidationOptions' threw an exception.
 ---> System.TypeInitializationException: The type initializer for 'Json.Schema.SchemaRegistry' threw an exception.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Json.Schema.JsonSchema.RegisterSubschemasAndGetBaseUri(SchemaRegistry registry, Uri currentUri)
   at Json.Schema.ItemsKeyword.Json.Schema.IRefResolvable.RegisterSubschemas(SchemaRegistry registry, Uri currentUri)
   at Json.Schema.JsonSchema.RegisterSubschemasAndGetBaseUri(SchemaRegistry registry, Uri currentUri)
   at Json.Schema.DefinitionsKeyword.Json.Schema.IRefResolvable.RegisterSubschemas(SchemaRegistry registry, Uri currentUri)
   at Json.Schema.JsonSchema.RegisterSubschemasAndGetBaseUri(SchemaRegistry registry, Uri currentUri)
   at Json.Schema.JsonSchema.RegisterSubschemas(SchemaRegistry registry, Uri currentUri)
   at Json.Schema.SchemaRegistry..cctor()
   --- End of inner exception stack trace ---
   at Json.Schema.SchemaRegistry..ctor(ValidationOptions options)
   at Json.Schema.ValidationOptions..ctor()
   at Json.Schema.ValidationOptions..cctor()
   --- End of inner exception stack trace ---
   at Json.Schema.ValidationOptions.get_Default()
```

The issue means that it is not possible to validate a `JsonElement` against a schema.

**To Reproduce**
```csharp
try {
    var options = Json.Schema.ValidationOptions.Default;
}
catch (Exception e) {
    Console.WriteLine(e.ToString());
}
```

**Expected behavior**
The type initialiser for `SchemaRegistry` should not throw a `NullReferenceException`.

### PR DESCRIPTION
**Pull request by gregsdennis**
Resolves #138

### CODE REVIEW

File: JsonSchema/SchemaRegistry.cs [hunk 1]
```diff
@@ -30,15 +28,25 @@ private class Registration
...
 		/// </summary>
-		public static SchemaRegistry Global { get; }
+		public static SchemaRegistry Global
+		{
+			get
+			{
+				_global._options ??= ValidationOptions.Default;
+				return _global;
+			}
+		}
```
Comment (gregsdennis) [inline JsonSchema/SchemaRegistry.cs:49]: Rather than initialize Global right away with the options, we wait until it's accessed.  By this time, the static `ValidationOptions.Default` will have been initialized, and we can safely set it here.
